ansible_connection: network_cli
ansible_user: sshuser
ansible_ssh_pass: sshpassword

borders:
  - { vrf: 'Voice', source: 'Loop11', reachable_test: [10.1.10.1, 10.3.10.1], unreachable_test: [192.168.1.1]}
  - { vrf: 'Clients', source: 'Loop10', reachable_test: [10.10.2.1, 192.168.3.1], unreachable_test: [10.0.0.1]}
  - { vrf: 'IOT', source: 'Loop9', reachable_test: [], unreachable_test: [192.168.1.1]}

cores:
  - { vrf: 'default', source: 'Vlan10', reachable_test: [10.1.100.1, 10.3.100.1, 10.2.100.1], unreachable_test: []}

ise:
  - 10.1.1.10
  - 10.1.1.11
dna:
  - 10.1.3.10
  - 10.1.3.11